### PR TITLE
Adding version and adding two-phased build.

### PR DESCRIPTION
**Pull request by lynxluna**
- Adds build date and commit number and output it on non-manual build.
- Adding flags to `go build' to produce self contained static binary
  without libc dependencies.
- Docker image is built using two phases
  build. This produces smaller docker build as the resultant image can be
  built from 'scratch' image

### CODE REVIEW

**Comment by lynxluna** [comment]
Let me state the primary reason for this PR:

- While I'm still doing UDP transport for this one I found out that the `Dockerfile` for this project was suboptimal. It includes the *whole* build system which is not needed for running the app. That's why I'm proposing to just build docker with static binary. This is actually the primary changes.
- `Dep` vs `Glide`, whichever work for the team, I'm okay with that. I might as well revert the changes, it's minor issue. As for the `vendor` dependencies. I'm in the side of not committing the vendor dep as it's actually useless if we have been locking the version using the `dep` or `glide` tool. CI server such as Travis will still fetch the remote dependencies wether it's from our repo or from other repo on every build so 'will fetch remotely' is moot point. If you want just speed up the build we can just cache them in the build server.
- If you read the build script, I didn't change the hard-coded `Version` `const`. What I inject during build are only the build date and the commit. What you might have concern that I write the whole version string in the `Version` field. 
- The reason why I think we need to print out the build date and commit hash is during deployment there maybe tons of binary deployments used by our team. Some may use some of our experimental builds of the same version. Printing build date/build number and commit will ease issue reporting as these are produced by the build server so this is less error prone. If your concern is the way I put the whole version string on `app.Version` then I can change it to be consistent, and maybe just move the printing on another place.

It may not be crucial and need some changes, but I think there's still value on this PR. I don't think this PR should be closed without any consideration.

**Comment by imantung** [comment]
My bad, so it does not change the version format :-p. But if we don't print Commit and Build inside the code. Is there any way to see it that from the binary file? How to utilize this? 
```
GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Commit=${TRAVIS_COMMIT} -X main.Build=$(date +%Y%m%d) -s -w" -o barito-flow-linux
```

Regarding the dependency tool and vendor folder. I think we can move to dep and exclude the vendor folder.

**Comment by lynxluna** [comment]
As you can see in the `main.go` you can see there's global variable in `main` module.

```
var (
	Commit string = "N/A"
	Build  string = "MANUAL"
)
```

The `-ldflags` arg will just override the default value of those vars. So if you want to use the value anywhere in the program, just refer to those vars.

**Comment by imantung** [comment]
Gotcha. It's nice to have Commit and Build too beside the version.

**Pull request merged**
